!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Saga=t():e.Saga=t()}(self,(function(){return function(){"use strict"
var e={554:function(e){e.exports=JSON.parse('[{"threshold":95,"canon":100,"color":"#8FB7E3","symbol":"++","title":"Preferred","description":"Agent is a first line therapy: reliably active in vitro, clinically effective, guideline recommended, recommended as a primary or acceptable alternative agent in the Sanford Guide. See pathogen page for specific recommendations."},{"threshold":81,"canon":90,"color":"#c2ffc0","symbol":"+","title":"Alternative","description":"Agent is a potential alternative agent (active in vitro, possesses class activity comparable to known effective agents or a therapeutically interchangeable agents and hence likely to be clinically effective) but second line due to overly broad spectrum, less favorable toxicity profile, less robust clinical experience or direct evidence of effectiveness."},{"threshold":51,"canon":75,"color":"#ffff87","symbol":"±","title":"Limited Utility","description":"Agent has variable or limited activity for one or more reasons: 1) although clinically effective in some settings or types of infection it is not reliably effective in others; 2) it should be used in combination with another agent; 3) it has efficacy limited by resistance; 4) there are proven effective alternatives with more favorable properties, e.g., pharmacokinetic profile, adverse events profile; 5) and/or clinical data to support its effectiveness are limited."},{"threshold":0,"canon":50,"color":"#fc7076","symbol":"0","title":"Not Recommended","description":"Agent is a poor alternative to other agents for one or more reasons: 1) lack of in vitro activity or resistance is likely to occur; 2) poor or undefined drug penetration at site of infection; 3) an unfavorable toxicity profile; 4) availability of proven effective or safer alternatives; 5) insufficient data to support dosing recommendations; or 6) lack of clinical data to support effectiveness."},{"threshold":-1,"canon":0,"color":"#C0C1C0","symbol":"?","title":"Insufficient Data","description":"Insufficient data to recommend use."}]')}},t={}
function s(a){var i=t[a]
if(void 0!==i)return i.exports
var n=t[a]={exports:{}}
return e[a](n,n.exports,s),n.exports}s.d=function(e,t){for(var a in t)s.o(t,a)&&!s.o(e,a)&&Object.defineProperty(e,a,{enumerable:!0,get:t[a]})},s.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)}
var a={}
s.d(a,{default:function(){return S}})
var i={SG_LAYER:56,CLEAR:"X",LEFT_COL_WIDTH:175,TOP_BAR_HEIGHT:175,CELL_DIMENSIONS:30,REC_GLUE:":",COLOR_MODE_DEFAULT:"default",LOCAL_STORAGE_KEY:"saga",FETCH_TIMEOUT:8e3,DATASET:{ANTIBACTERIAL:"antibacterial",ANTIFUNGAL:"antifungal",ANTIVIRAL:"antiviral"}}
function n(e){if(!e.ok)throw new Error(e.statusText)
return e}function o(e,t,s,a){let o=!1
new Promise((function(s,a){const r=setTimeout((function(){o=!0,a(new Error("Request timed out..."))}),i.FETCH_TIMEOUT)
fetch(e,t).then(n).then((e=>e.json())).then((e=>{clearTimeout(r),o||s(e)})).catch((function(e){o||a(e)}))})).then((e=>{s(e)})).catch((e=>{a(e)}))}class r{constructor(e,t){this.host=e,"string"==typeof t?(this.type="Basic",this.access_token=t):(this.type="Bearer",this.client_id=t.client_id,this.client_secret=t.client_secret,this.access_token=t.access_token,this.refresh_token=t.refresh_token)}headers(){return{Authorization:`${this.type} ${this.access_token}`,Accept:"application/json","Content-Type":"application/json"}}isTokenCurrent(){if("Basic"===this.type)return!0
let e=this.parseJwt(this.access_token)
return e&&1e3*e.exp>Date.now()}withHeaders(e,t){this.access_token?this.isTokenCurrent()?e(this.headers()):o(`${this.host}/oauth/token`,{method:"POST",cache:"no-cache",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({grant_type:"refresh_token",refresh_token:this.refresh_token,client_id:this.client_id,client_secret:this.client_secret,scope:""})},(t=>{this.access_token=t.access_token,this.refresh_token=t.refresh_token,e(this.headers())}),(e=>{t(e)})):t(new Error("No access token present."))}parseJwt(e){if(void 0===e)return{}
let t=e.split(".")[1].replace(/-/g,"+").replace(/_/g,"/"),s=decodeURIComponent(atob(t).split("").map((function(e){return"%"+("00"+e.charCodeAt(0).toString(16)).slice(-2)})).join(""))
return JSON.parse(s)}}const l=function(e,t){void 0===e&&(e=[])
let s=0,a=new Map
for(let i of e)i.sort_order=s++,a.set(i[t],i)
return a}
class h{constructor(e){this.loadData(e),this.dteChanges=!1}loadData(e){this.layers=l(e.layers,"asp_layer_id"),this.filters=l(e.filters,"asp_filter_id"),this.agents=l(e.agents,"id"),this.pathogens=l(e.pathogens,"id"),this.groups={agents:l(e.agent_groups,"id"),pathogens:l(e.pathogen_groups,"id")},this.filters.forEach((e=>{e.name=e.asp_filter_name})),this.standardizeRecommendations()}standardizeRecommendations(){this.flagAll("agents",!0),this.flagAll("pathogens",!0),this.layers.forEach((e=>{Array.isArray(e.recommendations)&&(e.recommendations={...e.recommendations})
for(let[t,s]of Object.entries(e.recommendations))if(Array.isArray(s)&&(e.recommendations[t]={value:s[0],isolates:s[1],comments:s[2]}),e.asp_layer_id===i.SG_LAYER){let[e,s]=t.split(i.REC_GLUE)
this.agents.get(parseInt(e)).institution_only=!1,this.pathogens.get(parseInt(s)).institution_only=!1}}))}flagAll(e,t){this[e].forEach((e=>e.institution_only=t))}agentKeys(){return Array.from(this.agents.keys())}pathogenKeys(){return Array.from(this.pathogens.keys())}markDteChanges(){this.dteChanges=!0}}const d=s(554)
class c{constructor(){this.resolved={}}find(e){return"number"!=typeof e&&(e=-1),this.resolved.hasOwnProperty(e)||(this.resolved[e]=d.find((t=>e>=t.threshold))||d[d.length-1]),this.resolved[e]}color(e){return this.find(e).color}symbol(e){return this.find(e).symbol}title(e){return this.find(e).title}getList(){return d}}function g(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},s=document.createElement(e)
for(let[e,a]of Object.entries(t))"readonly"===e&&!1===a||s.setAttribute(e,a)
for(var a=arguments.length,i=new Array(a>2?a-2:0),n=2;n<a;n++)i[n-2]=arguments[n]
for(let e of i)"object"!=typeof e&&(e=document.createTextNode(e)),s.appendChild(e)
return s}function p(e,t,s){let a=e.name.charAt(0)+"."
if(s>1){let t=(s-1)*i.CELL_DIMENSIONS,n=document.createElement("canvas").getContext("2d")
if(n.font="14px Helvetica, Arial, sans-serif",n.measureText(e.name).width<t)a=e.name
else if(e.cell_name&&n.measureText(e.cell_name).width<t)a=e.cell_name
else{let s=e.name.split(/[\s\-\/]+/).reduce(((e,t)=>e+t.charAt(0)),"").toUpperCase()
n.measureText(s).width<t&&(a=s)}}let n=g(a===e.name?"span":"abbr",{class:"saga-column-group-header",title:e.name},a)
return n.addEventListener("click",t),n}class u{constructor(e,t){this.enabled=e,this.host=t}href(e){return"file:"===window.location.protocol?e.split("/").pop()+".html":`${this.host}/${e}`}create(e){let{name:t,cell_name:s,url:a}=e,i=s||t
return this.enabled&&a?g("a",{target:"_parent",href:this.href(a),title:t,onclick:"event.stopPropagation()"},i):g(i===t?"span":"abbr",{title:t},i)}}const m="saga-modal-show",f="saga-modal-wide"
class y{constructor(){this.locked=!1,this.dialog=g("div",{class:"saga-modal-dialog"}),this.container=g("div",{class:"saga saga-modal-container"},this.dialog),this.container.addEventListener("click",(e=>{this.dialog.contains(e.target)||this.hide()})),this.close=g("div",{title:"Close",class:"saga-modal-close"}),this.close.addEventListener("click",(()=>{this.hide()})),document.body.appendChild(this.container)}unlock(){return this.locked=!1,this}lock(){return this.locked=!0,this}widen(){return this.dialog.classList.add(f),this}show(e){console.log("Showing Modal"),this.dialog.innerHTML="",this.locked||this.dialog.appendChild(this.close),this.dialog.appendChild("string"==typeof e?document.createTextNode(e):e),this.container.classList.add(m)}hide(){return console.log("Hiding Modal"),this.locked||(this.container.classList.remove(m),this.dialog.classList.remove(f)),this}}class v{constructor(e){this.storage_key=e}save(e){e.dteMode||localStorage.setItem(this.storage_key,JSON.stringify({layer_id:e.layer_id,transpose:e.transpose,visibility:e.visibility.dump(),known_models:{agents:e.data.agentKeys(),pathogens:e.data.pathogenKeys()}}))}load(){let e=(t=this.storage_key,JSON.parse(localStorage.getItem(t)||!1))
var t
return e||{}}}class _{constructor(e){this.sync("agents",e.agents||[]),this.sync("pathogens",e.pathogens||[])}dump(){return{agents:this.getEnabled("agents"),pathogens:this.getEnabled("pathogens")}}getEnabled(e){return Array.from(this[e].keys())}reset(){this.agents=new Map,this.pathogens=new Map}enable(e,t){this[e].set(parseInt(t),!0)}disable(e,t){this[e].delete(parseInt(t))}sync(e,t){this[e]=new Map
for(let s of t)this.enable(e,s)}rectify(e,t){console.log("Rectifying bugs/drugs"),e.data.agentKeys().filter((e=>!t.agents.includes(e))).forEach((e=>this.enable("agents",e))),e.data.pathogenKeys().filter((e=>!t.pathogens.includes(e))).forEach((e=>this.enable("pathogens",e)))}}class b{constructor(e){this.saga=e,this.html=g("div",{},g("h3",{},"Legend"),g("ul",{class:"saga-legend-list"},...e.legend.getList().map((e=>g("li",{},g("span",{style:`background: ${e.color}; padding: 2px`},`[${e.symbol}] ${e.title}`),g("span",{},`: ${e.description}`))))),g("p",{},"The data provided are intended to serve as a general guide to antibacterial usefulness based on treatment guidelines and recommendations, in vitro activity, predominant patterns of susceptibility or resistance and/or demonstrated clinical effectiveness. Variability in resistance patterns due to regional differences or as a consequent of clinical setting (e.g., community-onset vs. ICU-acquired infection) should be taken into account when using this table because activities of certain agents can differ significantly from what is shown in the table, which are by necessity based on aggregate information.")),this.saga.modal.widen().show(this.html)}}class w{constructor(e){this.saga=e,this.gray=e.isSanfordLayer(),this.sortByKey="index",this.sortByDir=1,this.searchTerm=""
let t=g("input",{type:"text",placeholder:"Search for...",spellcheck:"false",autocomplete:"off"})
t.addEventListener("input",(e=>{this.searchTerm=e.target.value.trim(),this.rerender()})),this.contents=g("div",{class:"saga-modal-suggestions"},t,this.render()),e.modal.widen().show(this.contents),t.focus()}rerender(){this.contents.replaceChild(this.render(),this.contents.childNodes[1])}arrayToTable(e){let t=e.map((e=>g("tr",{},g("th",{style:"width: 120px;"},e[0]),g("td",{style:"word-break: break-word;"},Array.isArray(e[1])?this.arrayToTable(e[1]):e[1]))))
return g("table",{class:"saga-alternating-table"},...t)}render(){if("uuddlrlrba"===this.searchTerm)return this.arrayToTable(this.saga.debugArray())
let e=g("div")
if(!this.searchTerm){let t=this.saga.commonActionsArray().map((e=>{let t=g("a",{},e.title)
return t.addEventListener("click",e.action),g("div",{},t)}))
e.appendChild(g("div",{class:"saga-three-up-columns"},...t))}let t=this.saga.data,s=this.search(t.filters,!1)
if(s.length){e.appendChild(g("h4",{class:"saga-modal-suggestions-title"},"Views"))
let t=g("div",{class:"saga-three-up-columns"})
for(let e of s){let s=g("a",{title:e.name},e.cell_name||e.name)
s.addEventListener("click",(t=>{t.stopPropagation(),this.saga.modal.hide(),this.saga.showFilter(e.asp_filter_id)}))
let a="";(e.user_id||this.saga.isEditor)&&(a=g("a",{class:"saga-filter-delete",title:`Delete ${e.name}`}),a.addEventListener("click",(t=>{t.stopPropagation(),confirm(`Really delete ${e.name}? This action cannot be undone.`)&&this.deleteFilter(e)}))),t.appendChild(g("div",{},a,s))}e.appendChild(t)}return this.suggestionSet(e,`${this.saga.nicknames.singular.y_axis} Groups`,this.search(t.groups.agents),(e=>{this.saga.showGroup("agents",e.id)})),this.suggestionSet(e,`${this.saga.nicknames.plural.y_axis}`,this.search(t.agents),(e=>{this.saga.showSingle("agents",e.id)}),(e=>e.institution_only)),this.suggestionSet(e,`${this.saga.nicknames.singular.x_axis} Groups`,this.search(t.groups.pathogens),(e=>{this.saga.showGroup("pathogens",e.id)})),this.suggestionSet(e,`${this.saga.nicknames.plural.x_axis}`,this.search(t.pathogens),(e=>{this.saga.showSingle("pathogens",e.id)}),(e=>e.institution_only)),e}search(e){let t=!(arguments.length>1&&void 0!==arguments[1])||arguments[1]
const s=this.searchTerm.toLowerCase()
let a=new Map
if(s){for(let[t,i]of e)for(let e of["name","cell_name"])if(i[e]&&i[e].toLowerCase().includes(s)){a.set(t,i)
break}}else a=e
return[...a.values()].map(((e,t)=>(e.index=t+1,e))).sort(((e,s)=>{if(t){if((e=e[this.sortByKey]||"zzzzzzzz")<(s=s[this.sortByKey]||"zzzzzzzz"))return-1*this.sortByDir
if(e>s)return this.sortByDir}return 0}))}suggestionSet(e,t,s,a){let i=arguments.length>4&&void 0!==arguments[4]?arguments[4]:null
if(!s.length)return
t&&e.appendChild(g("h4",{class:"saga-modal-suggestions-title"},t))
let n=g("span",{},"Name (click to sort)")
n.addEventListener("click",(e=>{e.stopPropagation(),this.setSort("name")}))
let o=g("span",{},"Abbr")
o.addEventListener("click",(e=>{e.stopPropagation(),this.setSort("cell_name")}))
let r=g("table",{class:"saga-alternating-table saga-sortable-table","data-table-of":t},g("tr",{},g("th",{},n),g("th",{style:"width:150px"},o)))
for(let e of s){let s=g("a",{"data-id":e.id},e.name)
this.gray&&i&&i(e)?(s.classList.add("saga-modal-suggestions-grayed"),s.addEventListener("click",(s=>{s.stopPropagation(),this.saga.dteMode?(e.institution_only=!1,this.saga.modal.hide(),a(e)):this.show(`\n              No Sanford Guide data exist for the selected ${t.slice(0,-1).toLowerCase()}.\n              Please switch to one of your institutional layers or select a similar item from the Sanford Guide data set.\n            `)}))):s.addEventListener("click",(t=>{t.stopPropagation(),this.saga.modal.hide(),a(e)})),r.appendChild(g("tr",{},g("td",{},s),g("td",{},e.cell_name||"-")))}e.appendChild(r)}deleteFilter(e){this.show("Deleting..."),this.saga.auth.withHeaders((t=>{fetch(`${this.saga.auth.host}/api/my/filter/${e.asp_filter_id}`,{method:"DELETE",cache:"no-cache",headers:t}).then(n).then((()=>{this.saga.data.filters.delete(e.asp_filter_id),this.show(`${e.asp_filter_name} deleted successfully.`)})).catch((e=>{this.show("Delete Error: "+e)}))}),(()=>{this.show("Could not delete filter (Fatal Authentication Error)")}))}show(e){this.saga.modal.hide().show(e)}setSort(e){e===this.sortByKey?1===this.sortByDir?this.sortByDir=-1:(this.sortByDir=1,this.sortByKey="index"):(this.sortByDir=1,this.sortByKey=e),this.rerender()}}class E{constructor(e){this.saga=e
let t=g("input",{type:"text",placeholder:"View Name",required:!0}),s=g("form",{},g("input",{type:"submit",value:"Create"}),g("div",{class:"saga-modal-save-view-submit"},t))
s.addEventListener("submit",(e=>{e.preventDefault(),this.save("POST",t.value)}))
let a=this.saga.nicknames.plural,i=g("div",{class:"saga-modal-save-view"},g("h2",{},"Save View"),g("p",{},`Enter the name you would like to describe this group of ${a.x_axis}/${a.y_axis}.`),s),n=Array.from(this.saga.data.filters.values()).filter((e=>e.user_id||this.saga.isEditor))
if(n.length){let e=g("select")
for(let t of n)e.appendChild(g("option",{value:t.asp_filter_id},t.asp_filter_name))
let t=g("form",{},g("input",{type:"submit",value:"Update"}),g("div",{class:"saga-modal-save-view-submit"},e))
t.addEventListener("submit",(t=>{t.preventDefault(),this.save("PUT",e.value)})),i.appendChild(g("p",{},"Or choose an existing view to update.")),i.appendChild(t)}this.show(i),t.focus()}save(e,t){let s=`${this.saga.auth.host}/api/my/filter`,a={content_bundle_profile_id:this.saga.data.layers.get(this.saga.layer_id).content_bundle_profile_id,asp_layer_id:this.saga.layer_id,asp_filter_transpose:this.saga.transpose}
"PUT"===e?s+="/"+t:a.asp_filter_name=t
let i=this.saga.visibility.dump()
this.show("Saving..."),this.saga.auth.withHeaders((t=>{fetch(s,{method:e,cache:"no-cache",headers:t,body:JSON.stringify({...a,...i})}).then(n).then((e=>e.json())).then((e=>{let t=e.data
this.saga.data.filters.set(t.asp_filter_id,{...t,...i,name:t.asp_filter_name}),this.show(`${t.asp_filter_name} saved successfully.`)})).catch((e=>{this.show("Save Error: "+e)}))}),(()=>{this.show("Could not save filter (Fatal Authentication Error)")}))}show(e){this.saga.modal.show(e)}}class A{constructor(e){this.saga=e
let t=this.saga.commonActionsArray().map((e=>this.makeButton(e.title,e.action)))
t.push(this.makeButton("Pivot Axes",(()=>this.saga.pivot()))),this.saga.isEditor&&t.push(this.makeButton("Save View",(e=>{e.stopPropagation(),new E(this.saga)}))),this.html=g("div",{},g("h3",{},"More Actions"),g("div",{class:"saga-more-action-buttons"},...t)),this.saga.modal.show(this.html)}makeButton(e,t){let s=g("a",{},e)
return s.addEventListener("click",t),s}}class C{constructor(e){this.saga=e,this.cache=g("div",{class:"saga-meta-cell"}),this.saga.element.appendChild(this.cache)}refresh(){if(console.log("Refreshing meta cell"),this.cache.innerHTML="",this.cache.classList.toggle("saga-meta-editor",this.saga.isEditor),this.saga.data.layers.size>1){let e=g("select")
for(let[t,s]of this.saga.data.layers){let a=g("option",{value:t,title:s.asp_layer_name},s.asp_layer_abbr)
t===this.saga.layer_id&&(a.selected=!0),e.appendChild(a)}e.addEventListener("change",(e=>{this.saga.setLayer(e.target.value)})),this.cache.appendChild(e)}let e=this.saga.nicknames.singular
this.appendButton(`Add ${e.x_axis}/${e.y_axis}`,(()=>this.openSuggestionModal())),this.appendButton("View SG Spectra",(()=>{this.saga.setLayer(i.SG_LAYER),this.saga.data.standardizeRecommendations(),this.saga.addAll("both",!1)})),this.cache.appendChild(g("hr")),this.appendButton("More Actions",(()=>new A(this.saga)))
let t=g("a",{class:this.saga.data.dteChanges?"":"saga-meta-secondary"})
this.saga.dteMode?(this.appendButton("Exit Editor",(()=>!this.saga.data.dteChanges||confirm("You have unsaved changes, are you sure you want to exit?")?location.href="../":0)),t.innerText="Save Changes",t.addEventListener("click",(()=>this.saveRecommendations()))):(t.innerText="See Legend",t.addEventListener("click",(()=>new b(this.saga)))),this.cache.append(g("div",{class:"saga-meta-button"},t))}appendButton(e,t){let s=g("a",{},e)
s.addEventListener("click",t),this.cache.appendChild(s)}saveRecommendations(){let e=`${this.saga.auth.host}/api/spectra/spectra-version/${this.saga.dataset}`
this.saga.modal.show("Saving..."),this.saga.auth.withHeaders((t=>{fetch(e,{method:"PATCH",cache:"no-cache",headers:t,body:JSON.stringify({recommendations:this.saga.getRecommendations()})}).then(n).then((e=>e.json())).then((e=>{this.saga.modal.show(`Saved successfully! (${e.created} created, ${e.updated} updated, ${e.deleted} deleted)`),this.saga.data.dteChanges=!1})).catch((e=>{this.saga.modal.show("Save Error: "+e)}))}),(()=>{this.saga.modal.show("Could not save (Fatal Authentication Error)")}))}openSuggestionModal(){return new w(this.saga)}}class k{constructor(e,t,s){this.saga=e,this.colKey=t,this.rowKey=s,this.showAll=!1,this.form=null,this.ajaxOutput=null,this.isEditing=!1,this.render()}render(){this.form=g("form",{class:"saga-modal-intersection"},this.saga.linker.create(this.saga.getAxisData("col",this.colKey)),g("span",{}," and "),this.saga.linker.create(this.saga.getAxisData("row",this.rowKey)),g("hr")),this.isEditing&&(this.ajaxOutput=g("div"),this.form.appendChild(this.ajaxOutput),this.form.addEventListener("submit",(e=>{e.preventDefault(),this.save()})))
for(let e of this.saga.data.layers.values())(this.showAll||e.asp_layer_id===this.saga.layer_id||e.asp_layer_id===i.SG_LAYER&&e.recommendations[this.saga.getRecommendationKey(this.colKey,this.rowKey)])&&this.form.appendChild(this.formatRecommendation(e))
let e=g("div",{class:"saga-modal-intersection-footer"})
if(this.saga.data.layers.size>1){let t=g("a",{},this.showAll?"Show Only Current Layer":"Show All Layers")
t.addEventListener("click",(e=>{e.stopPropagation(),this.showAll=!this.showAll,this.render()})),e.appendChild(t)}if(this.isEditing){e.appendChild(g("input",{type:"submit",value:"Save"}))
let t=g("a",{},"Cancel")
t.addEventListener("click",(e=>{e.stopPropagation(),this.saga.modal.hide()})),e.appendChild(t)}else if(this.saga.isEditor&&!this.saga.isSanfordLayer()){let t=g("a",{},"Edit")
t.addEventListener("click",(e=>{e.stopPropagation(),this.showAll=!1,this.isEditing=!0,this.render()})),e.appendChild(t)}this.form.appendChild(e),this.saga.modal.show(this.form)}formatRecommendation(e){var t
let s=this.isEditing&&e.asp_layer_id!==i.SG_LAYER,a=g("div",{class:"saga-modal-intersection-recommendation"},g("div",{title:e.asp_layer_abbr,style:"margin-bottom: 0.5em"},e.asp_layer_name),g("label",{for:`rec_value_${e.asp_layer_id}`},e.asp_layer_id===i.SG_LAYER?"Activity":"% Susceptible"))
e.asp_layer_id===this.saga.layer_id&&a.classList.add("saga-modal-intersection-recommendation-active")
let n=this.saga.getRecommendationKey(this.colKey,this.rowKey),o=e.recommendations[n]||{value:""},r=g("input",{id:`rec_value_${e.asp_layer_id}`,pattern:"[0-9]{0,3}",title:"Must be a whole number between 0 and 100",readonly:!s,placeholder:"no data",value:e.asp_layer_id===i.SG_LAYER?this.saga.legend.title(o.value):null!==(t=o.value)&&void 0!==t?t:""})
return r.style.background=this.saga.legend.color(o.value),a.appendChild(r),(o.isolates||s)&&(a.appendChild(g("label",{for:`isolates_${e.asp_layer_id}`,title:`Isolates for ${e.asp_layer_abbr}`},"Isolates")),a.appendChild(g("input",{id:`isolates_${e.asp_layer_id}`,pattern:"[0-9]{0,10}",title:"Must be a whole number",value:o.isolates||"",placeholder:"no data",readonly:!s}))),(o.comments||s)&&a.appendChild(g("textarea",{id:`comments_${e.asp_layer_id}`,placeholder:"Comments",readonly:!s},o.comments||"")),e.asp_layer_id===i.SG_LAYER&&(a.style.paddingBottom="1em"),a}save(){let e=`${this.saga.auth.host}/api/spectra/recommendation/batch?formatForSpectra=1`,t=[],[s,a]=this.saga.transpose?[this.rowKey,this.colKey]:[this.colKey,this.rowKey]
for(let e of this.saga.data.layers.keys()){if(e===i.SG_LAYER)continue
let n=this.getFormValue("rec_value",e),o=this.getFormValue("comments",e)
if(""!==n||""!==o){let i=this.getFormValue("isolates",e)
t.push({asp_pathogen_id:a,asp_agent_id:s,asp_layer_id:e,asp_recommendation_value:""!==n?parseInt(n):null,asp_recommendation_isolates:""!==i?parseInt(i):null,asp_recommendation_comments:o})}}t.length?(this.show("Saving..."),this.saga.auth.withHeaders((s=>{fetch(e,{method:"POST",cache:"no-cache",headers:s,body:JSON.stringify({entries:t})}).then(n).then((e=>e.json())).then((e=>{for(let[t,s]of Object.entries(e))for(let[e,a]of Object.entries(s))this.saga.data.layers.get(parseInt(t)).recommendations[e]=a
this.saga.rebuild("Rendering...")})).catch((e=>{this.show(e)}))}),(()=>{this.show("Could not save (Fatal Authentication Error)")}))):this.show("No data to save.")}show(e){this.ajaxOutput.classList.add("saga-intersection-ajax-output"),this.ajaxOutput.innerText=e}getFormValue(e,t){let s=this.form.querySelector(`#${e}_${t}`)
return s?s.value:""}}class L{constructor(e){this.saga=e,this.topBar=g("table",{class:"saga-top-bar"}),this.sideBar=g("table",{class:"saga-side-bar"}),this.tableElement=g("table",{class:"saga-main-table"}),this.overlay=g("div",{class:"saga-table-overlay"},"You do not have access to the Sanford Guide Activity Spectra.",g("br"),g("br"),"file:"===window.location.protocol?"Consider purchasing a subscription from us!":"Please log in to access it."),this.wrapperElement=g("div",{class:"saga-table-wrapper"},this.topBar,this.sideBar,this.tableElement),this.saga.element.appendChild(this.wrapperElement),this.saga.element.appendChild(this.overlay)}renderTop(){let e=this.getGroupedData("col")
this.topBar.innerHTML=""
let t=g("tr"),s=g("tr",{class:"saga-top-bar-cells-row"})
for(let[a,i]of e){if(!i.length)continue
let e=this.saga.getAxisGroupData("col",a)
t.appendChild(g("td",{class:"saga-top-group-name",colSpan:i.length},p(e,(()=>this.saga.modal.show(e.name+(e.cell_name?` (${e.cell_name})`:""))),i.length)))
for(let e of i){let t=g("td",{class:"saga-top-bar-cell"},g("div",{},this.saga.linker.create(e)))
e.cell_name&&(t.classList.add("saga-cell-has-comments"),t.addEventListener("click",(()=>this.saga.modal.show(e.name)))),s.appendChild(t)}}let a=g("td",{class:"saga-top-bar-cell",rowSpan:2},g("div",{},"Clear All Columns"))
a.addEventListener("click",(()=>this.saga.clearAxis("col"))),t.appendChild(a),this.topBar.appendChild(t),this.topBar.appendChild(s)}renderSide(){const e=this.getGroupedData("row")
this.sideBar.innerHTML=""
for(let[t,s]of e){if(!s.length)continue
let e=this.saga.getAxisGroupData("row",t)
this.sideBar.appendChild(g("tr",{},g("td",{class:"saga-side-bar-cell saga-row-group"},e.name)))
for(let e of s){let t=g("td",{class:"saga-side-bar-cell saga-side-bar-limit"},this.saga.linker.create(e))
e.cell_name&&(t.classList.add("saga-cell-has-comments"),t.addEventListener("click",(()=>this.saga.modal.show(e.name)))),this.sideBar.appendChild(g("tr",{},t))}}let t=g("tr",{},g("td",{class:"saga-side-bar-cell"},"Clear All Rows"))
t.addEventListener("click",(()=>this.saga.clearAxis("row"))),this.sideBar.appendChild(t)}renderMain(){let e=this.saga.getRecommendations()
const t=this.getGroupedData("col"),s=this.getGroupedData("row")
this.tableElement.innerHTML=""
for(let a of s.values())if(a.length){this.tableElement.appendChild(g("tr",{},g("td",{class:"saga-row-group",colSpan:1e3})))
for(let s of a){let a=g("tr",{class:"saga-cell-row"})
for(let i of t.values())if(i.length)for(let t of i)a.appendChild(this.getCellElement(t.id,s.id,e[this.saga.getRecommendationKey(t.id,s.id)]))
a.appendChild(this.getClearCellElement((()=>this.saga.clearSingle("row",s.id)))),this.tableElement.appendChild(a)}}let a=g("tr")
for(let e of t.values())if(e.length)for(let t of e)a.appendChild(this.getClearCellElement((()=>this.saga.clearSingle("col",t.id))))
a.appendChild(this.getClearCellElement((()=>this.saga.clearAll()))),this.tableElement.appendChild(a),this.overlay.style.display=this.saga.isSanfordLayer()&&!this.saga.dteMode&&0===Object.keys(e).length?"block":"none"}getGroupedData(e){let t=new Map
for(let s of this.saga.data.groups[this.saga.getAxisKey(e)].keys())t.set(s,[])
const s=this.saga.getAxisVisibility(e)
for(let a of s){let s=this.saga.getAxisData(e,a)
void 0!==s&&t.get(s.group_id).push(s)}return t}getCellElement(e,t){let s=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{},a=g("td",{class:"saga-cell","data-raw":JSON.stringify(e+":"+t)})
return this.saga.dteMode?(a.addEventListener("contextmenu",(a=>{a.preventDefault(),this.openIntersectionEdit("comments",s,a.target,e,t)})),a.addEventListener("click",(a=>this.openIntersectionEdit("value",s,a.target,e,t)))):a.addEventListener("click",(()=>this.openIntersectionModal(e,t))),this.styleCell(a,s)}styleCell(e,t){return e.title=t.comments,e.classList.toggle("saga-cell-has-comments",!!t.comments),void 0===t.value?(e.innerText="",e.style.backgroundColor="",e.classList.add("saga-no-recommendation"),e):(e.innerText=this.saga.isSanfordLayer()?this.saga.legend.symbol(t.value):t.value,e.style.backgroundColor=this.saga.legend.color(t.value),e)}getClearCellElement(e){let t=g("td",{class:"saga-cell saga-clear-cell"},i.CLEAR)
return t.addEventListener("click",e),t}openIntersectionEdit(e,t,s,a,i){let n=s.getBoundingClientRect(),o=g("div",{class:"saga-rec-edit-absolute"}),r=(e,n)=>{var o
let r=this.saga.getRecommendationKey(a,i),l=this.saga.getRecommendations()
null!==(o=t.value)&&void 0!==o||(t.value=0),t[e]=n,l[r]=t,this.styleCell(s,l[r]),this.saga.data.markDteChanges(),this.saga.metaCell.refresh()}
if("comments"===e){let e=g("textarea",{placeholder:"Enter comments...",rows:3},t.comments||"")
e.addEventListener("input",(e=>r("comments",e.target.value))),e.addEventListener("click",(e=>e.stopPropagation())),o.appendChild(e),setTimeout((()=>e.focus()),5)}else{for(let e of this.saga.legend.getList()){if(e.canon<0)continue
let t=g("div",{style:`background: ${e.color};`},g("div",{},e.symbol),g("div",{},e.title))
t.addEventListener("click",(()=>r("value",e.canon))),o.appendChild(t)}let e=g("div",{style:"background: white;"},g("div",{},"X"),g("div",{},"Delete"))
e.addEventListener("click",(()=>{let e=this.saga.getRecommendationKey(a,i)
delete this.saga.getRecommendations()[e],this.styleCell(s,{}),this.saga.data.markDteChanges(),this.saga.metaCell.refresh()})),o.appendChild(e)}let l=g("div",{class:"saga-rec-edit-container"},o),h=e=>{e.stopPropagation(),l.remove()}
l.addEventListener("contextmenu",h),l.addEventListener("click",h),this.saga.element.appendChild(l),o.style.left=n.x+"px",o.style.top=n.bottom+o.offsetHeight>window.innerHeight?n.top-o.offsetHeight+"px":n.bottom+"px"}openIntersectionModal(e,t){return new k(this.saga,e,t)}}class x{constructor(e){let{element:t="#saga-container",links:s=!0,api_host:a="https://naga.sanfordguide.com",dataset:n=i.DATASET.ANTIBACTERIAL,link_host:o,nicknames:l={},storage_key:d=i.LOCAL_STORAGE_KEY,saga_tokens:p={},saga_offline_data:m={},dte_mode:f=!1,default_transpose:b=!1}=e
this.SAGA_BUILD_VERSION="5.1.3",this.SAGA_BUILD_DATE="2025-05-06T18:00:15.911Z",this.dteMode=f,this.isEditor=!1,this.isOnline="unknown",this.nicknames={singular:{x_axis:l.x_axis_singular||"Bug",y_axis:l.y_axis_singular||"Drug"},plural:{x_axis:l.x_axis_plural||"Bugs",y_axis:l.y_axis_plural||"Drugs"}},this.dataset=n,this.auth=new r(a,p),this.data=new h(m),this.linker=new u(!!s,o||window.location.origin),this.modal=new y,this.storage=new v(d),this.hash=""
let w=this.storage.load()
return this.layer_id=w.layer_id||i.SG_LAYER,this.transpose=w.transpose||b,this.visibility=new _(w.visibility||{}),this.legend=new c,this.element=x.initElement(t),this.metaCell=new C(this),this.table=new L(this),this.fakeScroll=g("div",{class:"saga-fake-scroll"}),this.element.appendChild(this.fakeScroll),this.fetchData(),window.addEventListener("scroll",(()=>{let e=Math.max(window.scrollX||window.pageXOffset,0),t=Math.max(window.scrollY||window.pageYOffset,0)
this.setTransform(this.table.topBar,0,t),this.setTransform(this.table.sideBar,e,0),this.setTransform(this.table.wrapperElement,-e,-t)})),(this.inIframe()?window.parent:window).addEventListener("hashchange",(()=>{this.initView(),this.rebuild("Rendering...")})),this}setTransform(e,t,s){let a=`translate3d(${t}px, ${s}px, 0px)`
e.style.transform=a,e.style.WebkitTransform=a}setupFakeScroll(){this.fakeScroll.style.width=this.table.tableElement.scrollWidth+i.LEFT_COL_WIDTH+"px",this.fakeScroll.style.height=this.table.tableElement.scrollHeight+i.TOP_BAR_HEIGHT+"px"}rebuild(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"both"
this.modal.lock().show(e),window.requestAnimationFrame((()=>{window.requestAnimationFrame((()=>{"both"!==t&&"top"!==t||this.table.renderTop(),"both"!==t&&"side"!==t||this.table.renderSide(),this.table.renderMain(),this.setupFakeScroll(),this.modal.unlock().hide(),this.storage.save(this)}))}))}isSanfordLayer(){return this.layer_id===i.SG_LAYER}static initElement(e){return e instanceof HTMLElement||(e=document.querySelector(e)),e.innerHTML="",e.classList.add("saga"),e}initView(){const e=(this.inIframe()?window.parent:window).location
this.hash=decodeURI(e.hash.substring(1).toLowerCase())
const t=/(view|pathogen|drug)=(.*)/.exec(this.hash)
console.log("initView called with hash: "+this.hash)
let s=this.visibility
const a=(e,t)=>e.name.toLowerCase()===t||e.cell_name&&e.cell_name.toLowerCase()===t
switch(t&&t[1]){case"pathogen":const e=[...this.data.pathogens.values()].find((e=>a(e,t[2])))
e?(s.reset(),this.transpose=!0,s.enable("pathogens",e.id),Object.keys(this.getRecommendations()).filter((t=>t.endsWith(i.REC_GLUE+e.id))).forEach((e=>s.enable("agents",e.split(i.REC_GLUE).shift())))):console.warn(`Could not find matching pathogen for ${t[2]}`)
break
case"drug":const n=[...this.data.agents.values()].find((e=>a(e,t[2])))
n?(s.reset(),this.transpose=!1,s.enable("agents",n.id),Object.keys(this.getRecommendations()).filter((e=>e.startsWith(n.id+i.REC_GLUE))).forEach((e=>s.enable("pathogens",e.split(i.REC_GLUE).pop())))):console.warn(`Could not find matching agent for ${t[2]}`)
break
case"view":const o=[...this.data.filters.values()].find((e=>e.asp_filter_name.toLowerCase()===t[2]))
o?this.showFilter(o.asp_filter_id):console.warn(`Could not find matching filter for ${t[2]}`)}}fetchData(){let e=e=>{console.warn("Error Fetching Data",e),this.isOnline=e.toString(),this.afterFetch()}
this.modal.lock().show("Loading data..."),this.auth.withHeaders((t=>{let s="file:"===window.location.protocol?"apps":"web"
o(`${this.auth.host}/api/my/spectra/${this.dataset}?compacted=1&clientPlatform=${s}`,{cache:"no-cache",headers:t},(e=>{this.isEditor=!!e.data.editor,this.isOnline="online",this.data.loadData(e.data),this.afterFetch()}),e)}),e)}afterFetch(){console.log("After Fetch called"),this.data&&this.data.layers&&this.data.layers.has(this.layer_id)||(this.layer_id=i.SG_LAYER)
let e=this.storage.load()
void 0===e.visibility||void 0===e.known_models?this.addAll("both",!1):this.visibility.rectify(this,e.known_models),this.metaCell.refresh(),this.initView(),this.rebuild("Rendering...")}getAxisKey(e){return!this.transpose&&"col"===e||this.transpose&&"col"!==e?"agents":"pathogens"}reverseAxisKey(e){return!this.transpose&&"agents"===e||this.transpose&&"agents"!==e?"col":"row"}getAxisVisibility(e){let t=this.visibility.getEnabled(this.getAxisKey(e))
return this.isSanfordLayer()&&(t=t.filter((t=>{let s=this.getAxisData(e,t)
return s&&!s.institution_only}))),t.sort(((t,s)=>(t=this.getAxisData(e,t)||{sort_order:0},s=this.getAxisData(e,s)||{sort_order:0},Math.sign(t.sort_order-s.sort_order))))}getAxisData(e,t){return t=parseInt(t),this.data[this.getAxisKey(e)].get(t)}getAxisGroupData(e,t){return t=parseInt(t),this.data.groups[this.getAxisKey(e)].get(t)}getRecommendationKey(e,t){return(this.transpose?[t,e]:[e,t]).join(i.REC_GLUE)}getRecommendations(){let e=this.data.layers.get(this.layer_id)
return e?e.recommendations:{}}clearAll(){this.visibility.reset(),this.rebuild("Clearing All...")}clearAxis(e){this.visibility.sync(this.getAxisKey(e),[]),this.rebuild(`Clearing ${e}...`,this.rebuildOrientation(e))}clearSingle(e,t){this.visibility.disable(this.getAxisKey(e),t),this.rebuild(`Clearing ${e}...`,this.rebuildOrientation(e))}addAll(e,t){"both"!==e&&"agents"!==e||(t&&this.dteMode&&this.data.flagAll("agents",!1),this.visibility.sync("agents",this.data.agents.keys())),"both"!==e&&"pathogens"!==e||(t&&this.dteMode&&this.data.flagAll("pathogens",!1),this.visibility.sync("pathogens",this.data.pathogens.keys())),this.rebuild("Adding...")}showFilter(e){let t=this.data.filters.get(e)
this.visibility.reset()
for(let e of t.agents)this.visibility.enable("agents",e)
for(let e of t.pathogens)this.visibility.enable("pathogens",e)
this.transpose=!!t.asp_filter_transpose,this.setLayer(t.asp_layer_id),this.auth.withHeaders((t=>{fetch(`${this.auth.host}/api/my/filter/${e}/log`,{method:"POST",cache:"no-cache",headers:t})}),(()=>{}))}showGroup(e,t){for(let[s,a]of this.data[e])a.group_id===t&&this.visibility.enable(e,s)
this.rebuild(`Adding ${e} group...`,this.rebuildOrientation(this.reverseAxisKey(e)))}showSingle(e,t){this.visibility.enable(e,t),this.rebuild(`Adding ${e}...`,this.rebuildOrientation(this.reverseAxisKey(e)))}pivot(){this.transpose=!this.transpose,this.rebuild("Pivoting...")}setLayer(e){e=parseInt(e),this.data.layers.has(e)?(this.layer_id=e,this.metaCell.refresh(),this.rebuild("Rendering...")):this.modal.show(`Error: Layer ID ${e} is not available.`)}rebuildOrientation(e){return"row"===e?"side":"top"}inIframe(){return window.self!==window.top}commonActionsArray(){let e=this.nicknames.plural
return[{title:`Add All ${e.x_axis}`,action:()=>this.addAll("pathogens",!0)},{title:`Add All ${e.y_axis}`,action:()=>this.addAll("agents",!0)},{title:"Add Everything",action:()=>this.addAll("both",!0)},{title:`Clear All ${e.x_axis}`,action:()=>this.clearAxis(this.reverseAxisKey("pathogens"))},{title:`Clear All ${e.y_axis}`,action:()=>this.clearAxis(this.reverseAxisKey("agents"))},{title:"Clear Everything",action:()=>this.clearAll()}]}debugArray(){let e=[["Build version",this.SAGA_BUILD_VERSION],["Build date",this.SAGA_BUILD_DATE],["Api Host",this.auth.host],["Link Host",this.linker.host],["Is Editor",this.isEditor],["DTE Mode",this.dteMode],["Is Online",this.isOnline],["Is Pivoted",this.transpose],["In Iframe",this.inIframe()],["Table Width",this.table.tableElement.scrollWidth],["Table Height",this.table.tableElement.scrollHeight],["Hash",this.hash],["Access Token",this.auth.access_token],["Refresh Token",this.auth.refresh_token]]
return"Bearer"===this.auth.type&&e.push(["JWT",Object.entries(this.auth.parseJwt(this.auth.access_token))]),["Layers","Filters","Agents","Pathogens"].forEach((t=>e.push([t,this.data[t.toLowerCase()].size]))),e.push(["Agent Groups",this.data.groups.agents.size]),e.push(["Pathogen Groups",this.data.groups.pathogens.size]),e}}var S=x
return a=a.default}()}))
